services:
  xgc.core.controller:
    class: Xgc\CoreBundle\Service\CoreControllerService
    arguments: ["@xgc.request"]
    tags:
      - { name: kernel.event_subscriber }

  xgc.security:
    class: Xgc\CoreBundle\Service\SecurityService
    arguments: ["@doctrine", "@xgc.request", "@security.token_storage", "@event_dispatcher", "@security.password_encoder","%secret%"]

  xgc.request:
    class: Xgc\CoreBundle\Service\RequestService
    arguments: ["@request_stack"]
    calls:
      - [setExceptionHandler, ['@xgc.exception.handler']]

  xgc.exception.handler:
    class: Xgc\CoreBundle\Service\ExceptionHandlerService
    arguments: ["@service_container", "@xgc.request"]

  xgc.validator:
    class: Xgc\CoreBundle\Service\ValidatorService
    arguments: ["@validator"]

  xgc.settings:
    class: Xgc\CoreBundle\Service\SettingsService
    arguments: ["@doctrine", "@xgc.validator"]

  # Entities
  xgc.entity.user:
    class: Xgc\CoreBundle\Service\UserService
    arguments: ["@service_container"]
