imports:
  - { resource: parameters.yml }
  - { resource: security.yml }
  - { resource: services.yml }
  - { resource: xgc.yml }
  - { resource: "@WebBundle/Resources/config/services.yml" }
  - { resource: "@AdminBundle/Resources/config/services.yml" }
  - { resource: "@XgcCoreBundle/Resources/config/config.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  locale: es

framework:
  #esi:             ~
  #translator:      { fallbacks: ["%locale%"] }
  secret:          "%secret%"
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  form:            ~
  csrf_protection: ~
  validation:      { enable_annotations: true }
  #serializer:      { enable_annotations: true }
  templating:
    engines: ['twig']
  default_locale:  "%locale%"
  trusted_hosts:   ~
  trusted_proxies: ~
  session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    cookie_domain: ".%host_web%"
    cookie_path: '/'
    handler_id:  session.handler.native_file
    save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
  fragments:       ~
  http_method_override: true
  assets: ~
  php_errors:
    log: true

# Twig Configuration
twig:
  debug:            "%kernel.debug%"
  strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
  dbal:
    driver:   pdo_mysql
    host:     "%database_host%"
    port:     "%database_port%"
    dbname:   "%database_name%"
    user:     "%database_user%"
    password: "%database_password%"
    charset:  UTF8MB4
    default_table_options:
      charset: utf8mb4
      engine: ~
      collate: utf8mb4_general_ci

  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
  transport: "%mailer_transport%"
  host:      "%mailer_host%"
  username:  "%mailer_user%"
  password:  "%mailer_password%"
  spool:     { type: memory }

old_sound_rabbit_mq:
  connections:
    default:
      host:     'localhost'
      port:     5672
      user:     'guest'
      password: 'guest'
      vhost:    '/'


      lazy:     false
      connection_timeout: 3
      read_write_timeout: 3

      # requires php-amqplib v2.4.1+ and PHP5.4+
      keepalive: false

      # requires php-amqplib v2.4.1+
      heartbeat: 0

            #requires php_sockets.dll
            #use_socket: true # default false
  producers:
    upload_picture:
      connection:       default
      exchange_options: {name: 'upload-picture', type: direct}
      #service_alias:    test # no alias by default
  consumers:
    upload_picture:
      connection:       default
      exchange_options: {name: 'upload-picture', type: direct}
      queue_options:    {name: 'upload-picture'}
      callback:         test


nelmio_cors:
   defaults:
       allow_credentials: true
       allow_origin: ["*"]
       allow_headers: []
       allow_methods: ['POST', 'PUT', 'GET', 'DELETE','OPTIONS']
       expose_headers: []
       max_age: 0
       hosts: []
   paths:
    '^/':
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['origin', 'content-type']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE','OPTIONS']
        max_age: 0
        hosts: []

gos_web_socket:
  server:
    port: 8080        #The port the socket server will listen on
    host: 127.0.0.1   #The host ip to bind to
    router:
      resources:
        #- '@AdminBundle/Resources/config/pubsub/routing_rpc.yml'
        - '@AdminBundle/Resources/config/pubsub/routing_topic.yml'

assetic:
 bundles: [ XgcAdminLTEBundle, AdminBundle ]
 filters:
   scssphp:
     formatter: 'Leafo\ScssPhp\Formatter\Compressed'
   jsqueeze: ~
