xgc_core:
    exceptions:
        -
            host: "%host_api%"
            handler: "Xgc\\CoreBundle\\Exception\\ApiExceptionHandler"
        -
            host: "%host_admin%"
            handler: "Xgc\\CoreBundle\\Exception\\FlashExceptionHandler"

    versions:
        base: 0.0.9.7

    security:
        password:
            symbols: false
            numbers: true
            uppercases: true
            min_length: 8

xgc_sphinx:
    conf: "%kernel.root_dir%/config/sphinx/sphinx.conf"
    bin: ~

    #searchd:
        #host: localhost
        #port: 9312
    #indexes:
        #test1: "AppBundle:Commercial"

xgc_influx:
    host: localhost
    user: user
    pass: pass
    database: base_test
    port: 8086
