Xgc\CoreBundle\Entity\Entity:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
        fields:
            updatedAt:
                type: datetime
                nullable: false
            createdAt:
                type: datetime
                nullable: false

    lifecycleCallbacks:
        preUpdate: [__preUpdate]
        prePersist: [__prePersist]
