Xgc\CoreBundle\Entity\Setting:
  type: mappedSuperclass
  fields:
    key:
      column: _key
      type: string
      length: 32
      unique: true
    type:
      type: string
      length: 8
    value:
      type: string


